# wakanda-discovery/src/main/resources/application.yml
spring:
  application:
    name: wakanda-discovery
  cloud:
    discovery:
      enabled: true
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
