# wakanda-discovery/src/main/resources/application.yml
server:
  port: 8080 # Puerto del Gateway

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
          routes:
            # Ruta hacia el servicio Traffic
            - id: traffic-service
              uri: lb://TRAFFIC-SERVICE # El servicio se descubrir치 din치micamente en Eureka (load balancing)
              predicates:
                - Path=/traffic/**
              filters:
                - RewritePath=/traffic/(?<segment>.*), /$\\{segment} # Reescribe el path hacia el backend

            # Ruta hacia el servicio Energy
            - id: energy-service
              uri: lb://ENERGY-SERVICE
              predicates:
                - Path=/energy/**
              filters:
                - RewritePath=/energy/(?<segment>.*), /$\\{segment}

            # Ruta hacia el servicio Water
            - id: water-service
              uri: lb://WATER-SERVICE
              predicates:
                - Path=/water/**
              filters:
                - RewritePath=/water/(?<segment>.*), /$\\{segment}

          # Configuraci칩n de tiempo de espera para evitar problemas con peticiones
          default-filters:
            - name: CircuitBreaker # Habilitar Circuit Breaker en todas las rutas
              args:
                name: default
                fallbackUri: forward:/fallback

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Conexi칩n al servidor Eureka


# FallBack en caso de fallos en los servicios backend
management:
  endpoints:
    web:
      exposure:
        include: "*"