services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Puerto AMQP
      - "15672:15672"  # Interfaz de administración
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
    networks:
      - my-network

  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: eureka
    networks:
      - my-network

  health-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: health-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: health
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: myuser
      SPRING_RABBITMQ_PASSWORD: mypassword
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - rabbitmq
      - eureka-server
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
