# wakanda-services/src/main/resources/application.yml
server:
  port: 8081

spring:
  application:
    name: traffic-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
