# wakanda-gateway/src/main/resources/application.yml
server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: traffic-service
          uri: lb://TRAFFIC-SERVICE
          predicates:
            - Path=/traffic/**
        - id: energy-service
          uri: lb://ENERGY-SERVICE
          predicates:
            - Path=/energy/**
        - id: water-service
          uri: lb://WATER-SERVICE
          predicates:
            - Path=/water/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
